version: "3.8"

services:
  app:
    env_file: .env
    image: ghcr.io/stuartmaxwell/stuartmnz:latest
    entrypoint: /app/entrypoint.sh
    restart: always
    command: gunicorn --worker-tmp-dir /dev/shm --workers=2 --worker-class=gthread --bind 0.0.0.0:8000 config.wsgi
    user: "1000"
    volumes:
      - static_volume:/app

volumes:
  static_volume:
