services:
  app:
    build: .
    entrypoint: /app/entrypoint.sh
    command: uv run --no-cache gunicorn --worker-class uvicorn_worker.UvicornWorker --worker-tmp-dir /dev/shm --workers=2 --max-requests=1000 --max-requests-jitter=50 --bind 0.0.0.0:8000 config.asgi:application
    user: "1000"
    env_file: .env
    volumes:
      - app_db:/app/db

volumes:
  app_db:
