[project]
name = "stuartm-nz"
version = "0.15.0"
description = "stuartm.nz"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "django-environ>=0.11.2",
  "django~=5.1.0",
  "djpress~=0.16.0b",
  "whitenoise>=6.7.0",
  "gunicorn>=23.0.0",
  "rich>=13.8.1",
  "sentry-sdk>=2.14.0",
  "django-debug-toolbar>=4.4.6",
  "pytest>=8.3.3",
  "pytest-django>=4.9.0",
  "mistune>=3.0.2",
  "pygments>=2.18.0",
  "djpress-publish-mastodon>=1.0.0",
  "httpx>=0.27.2",
  "uvicorn>=0.32.1",
  "uvicorn-worker>=0.2.0",
  "logfire[asgi,django]>=2.5.0",
  "djpress-publish-bluesky>=1.0.0",
]

[tool.curlylint.rules]
image_alt = true

[tool.ruff]
select = ["ALL"]
ignore = [
  "G004",   # Logging statement uses f-string
  "D203",   # 1 blank line required before class docstring
  "D213",   # multi-line-summary-second-line
  "TD003",  # Missing issue link on the line following this TODO
  "FIX002", # Line contains TODO, consider resolving the issue
  "TD002",  # Missing author in TODO
  "S308",   # suspicious-mark-safe-usage
]
line-length = 120

target-version = "py313"

[tool.ruff.per-file-ignores]
"test*" = ["ALL"]
"**/migrations/*" = ["ALL"]
"manage.py" = ["ALL"]

[tool.ruff.lint.pydocstyle]
convention = "google" # Accepts: "google", "numpy", or "pep257".

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings_testing"
python_files = "tests.py test_*.py *_tests.py"
