# Generated by Django 5.1.3 on 2024-11-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    # pyrefly: ignore [bad-override]
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the email provider (e.g., 'Google Workspace', 'SendGrid')", max_length=100, unique=True)),
                ('category', models.CharField(choices=[('EMAIL_HOSTING', 'Email Hosting'), ('TRANSACTIONAL', 'Transactional Email'), ('OTHER', 'Other')], help_text='Category of email provider', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Public description of the provider')),
                ('mechanism_type', models.CharField(choices=[('include', 'Include'), ('a', 'A Record'), ('mx', 'MX Record'), ('ip4', 'IPv4'), ('ip6', 'IPv6'), ('exists', 'Exists')], help_text='Type of SPF mechanism used', max_length=10)),
                ('mechanism_value', models.CharField(help_text="The actual SPF mechanism value (e.g., 'include:_spf.google.com')", max_length=255)),
                ('lookup_count', models.PositiveSmallIntegerField(default=1, help_text='Number of DNS lookups this mechanism requires')),
                ('priority', models.PositiveSmallIntegerField(default=100, help_text='Order in which this should appear in combined SPF record')),
                ('active', models.BooleanField(default=True, help_text='Whether this provider is currently available for selection')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this provider')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
    ]
