# Generated by Django 5.0.4 on 2024-04-25 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djpress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
