# Generated by Django 5.0.4 on 2024-04-25 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djpress', '0002_alter_content_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='content',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
