# Generated by Django 5.0.4 on 2024-04-25 07:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djpress', '0003_alter_content_date_alter_content_modified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
