# Generated by Django 5.0.4 on 2024-04-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djpress', '0004_alter_content_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
