# Generated by Django 5.0.4 on 2024-04-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djpress', '0005_alter_content_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
