# Generated by Django 5.0.4 on 2024-05-01 10:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djpress', '0007_alter_content_managers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Content',
            new_name='Post',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'catregories'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'content', 'verbose_name_plural': 'contents'},
        ),
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
    ]
