name: Update Dependencies

on:
  workflow_dispatch:  # manual trigger only

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2

      - name: Update dependencies
        run: uv sync --all-extras --upgrade

      - name: Run tests
        run: uv run --extra test --locked pytest

      - name: Create and switch to new branch
        run: |
          git checkout -b dependency-updates-${{ steps.date.outputs.date }}
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "chore: update dependencies"
          git push origin dependency-updates-${{ steps.date.outputs.date }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          base: main
          branch: dependency-updates-${{ steps.date.outputs.date }}
